import os
from dotenv import load_dotenv


load_dotenv(override=True)


YANDEX_MAPS_API_KEY = os.getenv("YANDEX_MAPS_API_KEY")

POSTGRES_USER=os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD=os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB=os.getenv("POSTGRES_DB")

MLFLOW_PORT=5050
S3_API_PORT=9000
S3_UI_PORT=9001

MLFLOW_S3_ENDPOINT_URL="http://localhost:9000"
MINIO_ROOT_USER=os.getenv("MINIO_ROOT_USER")
MINIO_ROOT_PASSWORD=os.getenv("MINIO_ROOT_PASSWORD")
DEFAULT_BUCKET_NAME=os.getenv("DEFAULT_BUCKET_NAME")